/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AttachmentsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ConfigTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EmailDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EmailWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "JobsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}